### ISSUE TITLE
The settings are not displayed

### ISSUE THREAD

**Issue by oFFraid** [jenkinsci/jetbrains-space-plugin#30]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

OS: macos Monterey 12.7.5
Browser: Google Chrome 126.0.6478.127
Jenkins 2.452.2

### Reproduction steps

1. install plugin 2. locate to /manage/spacecode/

### Expected Results

displaying plugin settings

### Actual Results

Plugin settings is empty 
<img width="1424" alt="image" src="https://github.com/jenkinsci/jetbrains-space-plugin/assets/57768785/459e1434-6593-49b5-a77f-395fa6508878">

and 2 errors in console 

<img width="1424" alt="image" src="https://github.com/jenkinsci/jetbrains-space-plugin/assets/57768785/b360a535-b7a1-4316-80a3-330e09e7ca4d">

**Comment by Kiryushin-Andrey** [comment]
Hi @oFFraid,
It looks like the page couldn't load either its content or the javascript from the server due to some origin issues that shouldn't be there (probably http/https, or a wrong host name). Could you please show the contents of the network tab of the browser development tools so that I can see the failed requests and their URLs?

**Comment by oFFraid** [comment]
Hi @Kiryushin-Andrey. Here is a screenshot from the network tab. All requests have a status of 200. The host address (the one that is painted over) is ip:port of my Jenkins server.
![image](https://github.com/jenkinsci/jetbrains-space-plugin/assets/57768785/55c6fb17-ad32-4b37-9d7e-84f18d9127cc)
